import type { Species, SpeciesId } from "../engine/types";

export const SPECIES: Record<SpeciesId, Species> = {
  cat: {
    id: "cat",
    nameTr: "Kedi",
    nameEn: "Cat",
    emoji: "🐱",
    climb: "jump",
    speed: 2.4,
    hopWalk: false,
    floatIdle: false,
    mass: 1,
    scale: 1,
    sound: "miyav",
    blurb: "Pencerelere zıplayarak çıkar, öne gelince büyür.",
  },
  dog: {
    id: "dog",
    nameTr: "Köpek",
    nameEn: "Dog",
    emoji: "🐶",
    climb: "jump",
    speed: 2.6,
    hopWalk: false,
    floatIdle: false,
    mass: 1.1,
    scale: 1.05,
    sound: "hav hav",
    blurb: "Neşeli havlar, pencerelere zıplar.",
  },
  turtle: {
    id: "turtle",
    nameTr: "Kaplumbağa",
    nameEn: "Turtle",
    emoji: "🐢",
    climb: "jump",
    speed: 0.85,
    hopWalk: false,
    floatIdle: false,
    mass: 1.4,
    scale: 0.9,
    sound: "tok tok",
    blurb: "Yavaş yürür, kısa zıplayışlarla tırmanır.",
  },
  elephant: {
    id: "elephant",
    nameTr: "Fil",
    nameEn: "Elephant",
    emoji: "🐘",
    climb: "jump",
    speed: 1.35,
    hopWalk: false,
    floatIdle: false,
    mass: 2.2,
    scale: 1.35,
    sound: "büüü",
    blurb: "Ağır zıplar, yere inince gürültü yapar.",
  },
  bird: {
    id: "bird",
    nameTr: "Kuş",
    nameEn: "Bird",
    emoji: "🐦",
    climb: "fly",
    speed: 3.1,
    hopWalk: false,
    floatIdle: true,
    mass: 0.4,
    scale: 0.72,
    sound: "cik cik",
    blurb: "Pencerelere uçarak çıkar, cik cik öter.",
  },
  eagle: {
    id: "eagle",
    nameTr: "Kartal",
    nameEn: "Eagle",
    emoji: "🦅",
    climb: "fly",
    speed: 2.8,
    hopWalk: false,
    floatIdle: true,
    mass: 0.7,
    scale: 1.05,
    sound: "kriii",
    blurb: "Kanat çırparak süzülür, yüksek tüneğe uçar.",
  },
  ghost: {
    id: "ghost",
    nameTr: "Hayalet",
    nameEn: "Ghost",
    emoji: "👻",
    climb: "fly",
    speed: 2.2,
    hopWalk: false,
    floatIdle: true,
    mass: 0.3,
    scale: 1,
    sound: "buggg",
    blurb: "Uçarak gezer, öne gelince şeffaf devleşir.",
  },
  rabbit: {
    id: "rabbit",
    nameTr: "Tavşan",
    nameEn: "Rabbit",
    emoji: "🐰",
    climb: "jump",
    speed: 2.7,
    hopWalk: true,
    floatIdle: false,
    mass: 0.8,
    scale: 0.88,
    sound: "piy piy",
    blurb: "Zıplayarak yürür, pencerelere hoplar.",
  },
};

export const SPECIES_ORDER: SpeciesId[] = [
  "cat",
  "dog",
  "rabbit",
  "turtle",
  "elephant",
  "bird",
  "eagle",
  "ghost",
];
